-- ============================================
-- Supabase Clean Production Database Setup
-- Veerabhadra Pooja Store
-- Run this in Supabase SQL Editor (one time only)
-- ============================================

-- 1. Sequence for auto-generating order IDs starting from VRB100001
CREATE SEQUENCE IF NOT EXISTS order_id_seq START WITH 100001;

-- 2. Function to generate VRB-prefixed order IDs (VRB100001, VRB100002, ...)
CREATE OR REPLACE FUNCTION generate_order_id()
RETURNS TEXT AS $$
BEGIN
  RETURN 'VRB' || nextval('order_id_seq')::TEXT;
END;
$$ LANGUAGE plpgsql;

-- 3. Create orders table
CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY DEFAULT generate_order_id(),
  user_id TEXT,
  customer_name TEXT NOT NULL DEFAULT 'WhatsApp Customer',
  mobile_number TEXT DEFAULT 'Via WhatsApp',
  address TEXT DEFAULT 'Provided via WhatsApp',
  order_date TEXT,
  items JSONB DEFAULT '[]'::jsonb,
  total_amount NUMERIC DEFAULT 0,
  payment_method TEXT DEFAULT 'UPI/Cash',
  status TEXT DEFAULT 'Pending',
  notification_history JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure user_id column exists
ALTER TABLE orders ADD COLUMN IF NOT EXISTS user_id TEXT;

-- 4. Enable Row Level Security (RLS) with full public access policies
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Clean up older policies if re-running script
DROP POLICY IF EXISTS "Allow public read" ON orders;
DROP POLICY IF EXISTS "Allow public insert" ON orders;
DROP POLICY IF EXISTS "Allow public update" ON orders;
DROP POLICY IF EXISTS "Allow public delete" ON orders;

-- Define RLS Policies for production web application
CREATE POLICY "Allow public read" ON orders FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON orders FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete" ON orders FOR DELETE USING (true);

-- 5. Performance Indexes
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);

-- 6. Stock Notifications Table (Back-in-Stock Alerts)
CREATE TABLE IF NOT EXISTS stock_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id TEXT NOT NULL,
  product_name TEXT NOT NULL,
  customer_name TEXT DEFAULT 'Customer',
  mobile_number TEXT NOT NULL,
  notified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE stock_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert notification" ON stock_notifications;
DROP POLICY IF EXISTS "Allow public select notification" ON stock_notifications;
DROP POLICY IF EXISTS "Allow public update notification" ON stock_notifications;

CREATE POLICY "Allow public insert notification" ON stock_notifications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select notification" ON stock_notifications FOR SELECT USING (true);
CREATE POLICY "Allow public update notification" ON stock_notifications FOR UPDATE USING (true);

CREATE INDEX IF NOT EXISTS idx_stock_notif_product ON stock_notifications(product_id, notified);

